In [2]:
pd.read_pickle("sqanti/at6929_pb_augustus_sqanti_orf.pkl").head()

,Gene,n ORFs,n Isoforms,Sqanti ORFs,Isoforms,n_Isoforms_ORF,Subcategories,Read_Support,Read_Support_ORF
0,PB,135423,300219,[MGKEKFHINIVVIGHVDSGKSTTTGHLIYKLGGIDKRVIERFEKE...,"[[PB.477.10, PB.477.11, PB.477.13, PB.477.15, ...","[316, 205, 188, 185, 156, 155, 149, 140, 139, ...","[[at_least_one_novel_splicesite, at_least_one_...","[[1, 1, 1, 1, 8, 1, 1, 6, 1, 22, 161, 1, 1, 4,...","[7484, 233, 1082, 4482, 209, 2490, 828, 151, 2..."

In [8]:
pd.read_pickle("merged/at6923_pb_augustus_merged.pkl").head()

,isoform,exons,length,structural_category,associated_gene,associated_transcript,subcategory,ORF_seq,gene,isoform_reads,gene_reads,accession
0,PB.1.1,9,849,novel_not_in_catalog,g2,novel,at_least_one_novel_splicesite,MAASEHRCVGCGFRVKSLFIQYSPGNIRLMKCGNCKEVADEYIECE...,PB1,1,2,at6923
1,PB.1.2,6,1381,novel_not_in_catalog,g2,novel,intron_retention,MAASEHRCVGCGFRVKSLFIQYSPGNIRLMKCGNCKEVADEYIECE...,PB1,1,2,at6923
2,PB.10.1,1,1804,antisense,novelGene_g8_AS,novel,mono-exon,NaN,PB10,1,1,at6923
3,PB.100.1,11,1387,novel_not_in_catalog,g132,novel,at_least_one_novel_splicesite,MGAWLYFKYHGVVTQECDPYFDNTGCSHPGCEPTYPTPKCERKCVS...,PB100,1,22,at6923
4,PB.100.10,10,1274,novel_not_in_catalog,g132,novel,at_least_one_novel_splicesite,MGAWLYFKYHGVVTQECDPYFDNTGCSHPGCEPTYPTPKCERKCVS...,PB100,2,22,at6923

In [6]:
pd.read_pickle("sqanti/at7143_tama_liftoff_sqanti_orf.pkl").head()

,Gene,n ORFs,n Isoforms,Sqanti ORFs,Isoforms,n_Isoforms_ORF,Subcategories,Read_Support,Read_Support_ORF
0,G1,0,0,[],[],[],[],[],[]
0,G10,1,1,[MNTRHPKCRTFLPNLGVRSGSQVRHPNGPQVILDNKDNRQFIESS...,[[G10.1]],[1],[[multi-exon]],[[1]],[1]
0,G100,1,5,[MSGNKISTLQALVFFLYRFFILRRWCHRSPKQKYQKCPSHGLHQY...,"[[G100.1, G100.2, G100.3, G100.4, G100.5]]",[5],"[[reference_match, reference_match, alternativ...","[[2, 2, 1, 2, 1]]",[8]
0,G1000,2,4,[MNLSHRVGSRFHTASLEASSSANNPFAEGSGEMSPGPSIPLRRAA...,"[[G1000.1, G1000.2, G1000.4], [G1000.3]]","[3, 1]","[[reference_match, reference_match, alternativ...","[[1, 1, 1], [1]]","[3, 1]"
0,G10000,2,5,[MERNCRRNLEREGINGIGCVWVFISLFGSNQKRLLMDNKRGSKRV...,"[[G10000.1, G10000.2, G10000.3, G10000.4], [G1...","[4, 1]","[[alternative_5end, at_least_one_novel_splices...","[[1, 1, 1, 1], [2]]","[4, 2]"

In [5]:
pd.read_pickle("sqanti/at7143_pb_augustus_sqanti_orf.pkl").head()

,Gene,n ORFs,n Isoforms,Sqanti ORFs,Isoforms,n_Isoforms_ORF,Subcategories,Read_Support,Read_Support_ORF
0,PB,148734,338921,[MGKEKFHINIVVIGHVDSGKSTTTGHLIYKLGGIDKRVIERFEKE...,"[[PB.503.1, PB.503.11, PB.503.13, PB.503.14, P...","[298, 226, 221, 187, 182, 177, 171, 159, 154, ...","[[at_least_one_novel_splicesite, at_least_one_...","[[8, 97, 6, 3, 9, 4, 3, 10, 1, 3, 1, 2, 7, 1, ...","[9150, 4119, 268, 1395, 3618, 1212, 202, 1950,..."

In [1]:
import warnings
warnings.simplefilter(action='ignore')
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import os
from tqdm import tqdm

In [9]:
def plot_distribution(df, attribute, coloring, run, relation, combination, acc):
    palette ={"nlr": "C0", "busco": "C1", "housekeeping": "C2", "all": "C3", "rest":"C3"}
    order=["nlr","busco","housekeeping"] if combination == "reference" else ["nlr","busco","housekeeping", "all"] if combination == "background" else ["nlr","busco","housekeeping", "rest"]
    sns.displot(df, x=attribute, hue = coloring, kind="kde",common_norm=False, palette=palette, hue_order=order)
    plt.savefig("{}/{}/{}/{}_tama_liftoff_{}_{}.png".format(run,acc,relation,acc,combination,attribute), bbox_inches='tight')
    plt.close()

In [10]:
def plot_categories(df, attribute, coloring, run, relation, combination, acc):
    palette ={"nlr": "C0", "busco": "C1", "housekeeping": "C2", "all": "C3", "rest":"C3"}
    order=["nlr","busco","housekeeping"] if combination == "reference" else ["nlr","busco","housekeeping", "all"] if combination == "background" else ["nlr","busco","housekeeping", "rest"]
    sns.histplot(df, x=attribute, hue =coloring, multiple= "dodge", stat="percent", common_norm=False, shrink = 0.8,  palette=palette, hue_order=order)
    plt.xticks(rotation=45, horizontalalignment='right')
    plt.savefig("{}/{}/{}/{}_tama_liftoff_{}_{}.png".format(run,acc,relation,acc,combination,attribute), bbox_inches='tight')
    plt.close()

# Preparation of reference gene lists

In [6]:
busco = pd.read_csv("/ebio/abt6_projects7/dliso/dlis/leon_pipeline/analysis/sqanti/ref_genes/busco_Araport11_20221221.txt", header=None)
house = pd.read_csv("/ebio/abt6_projects7/dliso/dlis/leon_pipeline/analysis/sqanti/ref_genes/arat_housekeeping.txt", header=None)
nlr = pd.read_csv("/ebio/abt6_projects7/dliso/dlis/leon_pipeline/analysis/sqanti/ref_genes/nlrs_in_orthogroups_20221221.txt", header=None)

In [7]:
busco["type"] = "busco"
house["type"] = "housekeeping"
nlr["type"] = "nlr"
gene_type = pd.concat([busco,house,nlr])
gene_type.columns = ["ref_isoform","type"]
gene_type = gene_type.groupby("ref_isoform")["type"].apply(', '.join).reset_index()

In [8]:
gene_type["ref_gene"] = gene_type["ref_isoform"].str.split(".").str[0]
gene_type.loc[gene_type["type"] == "busco, nlr"] = "nlr"
gene_type.loc[gene_type["type"] == "housekeeping, nlr"] = "nlr"
gene_type.loc[gene_type["type"] == "busco, housekeeping"] = "housekeeping"
print(gene_type["type"].value_counts())

busco           4483
housekeeping     704
nlr              252
Name: type, dtype: int64

# FULL RUN

In [12]:
accessions= ['at6923','at6929','at7143','at8285','at9104','at9336','at9503','at9578','at9744','at9762','at9806','at9830','at9847','at9852','at9879','at9883','at9900','col0']
#accessions= ['at6923']

#runs=["full","iso2","gene2"]
runs=["full"]


for run in tqdm(runs):
    tama_liftoff_df = pd.DataFrame()
    tama_subcat = pd.DataFrame()
    for acc in tqdm(accessions):
        # -------------0-------------
        # make directories
        os.makedirs("{}/{}/isoform".format(run,acc), exist_ok=True)
        os.makedirs("{}/{}/gene".format(run,acc), exist_ok=True)
        # -------------1-------------
        # prepare sqanti output
        sqanti = pd.read_csv("/ebio/abt6_projects7/dliso/dlis/leon_pipeline/output/v2/collapse_tama/{}_liftoff_sqanti/{}-tama-vs-liftoff_classification.txt".format(acc,acc), sep="\t")
        sub = sqanti[["isoform","exons","length","structural_category","associated_gene","associated_transcript","subcategory","ORF_seq"]]
        sub["gene"] = sub["isoform"].str.split(".").str[0]

        # -------------3-------------
        # prepare read support
        reads = pd.read_csv("/ebio/abt6_projects7/dliso/dlis/leon_pipeline/output/v2/collapse_tama/{}.collapsed.tama.v2_read_support.txt".format(acc), sep="\t")
        r_sub = reads[["merge_trans_id","trans_read_count","gene_read_count"]]
        r_sub.columns = ["isoform", "isoform_reads", "gene_reads"]

        # -------------4-------------
        # add accession ID and merge all information
        merged_all = pd.merge(left=sub, right=r_sub, how='left', left_on='isoform', right_on='isoform')
        merged_all['accession'] = acc

        # set dataset to work with
        if run == "iso2":
            merged_all=merged_all[merged_all["isoform_reads"]>1]
        elif run == "gene2":
            merged_all=merged_all[merged_all["gene_reads"]>1]

        tama_liftoff_df = pd.concat([tama_liftoff_df, merged_all])

        # -------------5-------------
        # relate the gene type to their isoform in sqanti
        iso_ref = pd.merge(left=merged_all, right=gene_type, how='left', left_on='associated_transcript', right_on='ref_isoform')
        # ------------5.1------------
        # basic analysis
        iso_nlr = iso_ref.loc[iso_ref["type"] == "nlr"]
        iso_busco = iso_ref.loc[iso_ref["type"] == "busco"]
        iso_house = iso_ref.loc[iso_ref["type"] == "housekeeping"]
        iso_all = pd.concat([iso_nlr,iso_busco,iso_house])
        # plot exon + length distribution
        plot_distribution(iso_all, "exons", "type", run, "isoform", "reference", acc)
        plot_distribution(iso_all, "length", "type", run,  "isoform", "reference", acc)
        # plot category and subcategory
        plot_categories(iso_all, "structural_category", "type", run, "isoform", "reference", acc)
        plot_categories(iso_all, "subcategory", "type", run,  "isoform", "reference", acc)
        # ------------5.2------------
        # all genes as background, reference genes on top
        gene_background = merged_all.copy()
        gene_background["ref_isoform"] = "None"
        gene_background["type"] = "all"
        gene_background["ref_gene"] = "None"
        iso_background_all = pd.concat([iso_all,gene_background], ignore_index=True)
        # plot exon + length distribution
        plot_distribution(iso_background_all, "exons", "type", run, "isoform", "background", acc)
        plot_distribution(iso_background_all, "length", "type", run,  "isoform", "background", acc)
        # plot category and subcategory
        plot_categories(iso_background_all, "structural_category", "type", run, "isoform", "background", acc)
        plot_categories(iso_background_all, "subcategory", "type", run,  "isoform", "background", acc)
        # ------------5.3------------
        # rest vs. busco vs. house vs nlr.
        iso_ava = iso_ref.fillna("rest")
        # plot exon + length distribution
        plot_distribution(iso_ava, "exons", "type", run, "isoform", "ava", acc)
        plot_distribution(iso_ava, "length", "type", run,  "isoform", "ava", acc)
        # plot category and subcategory
        plot_categories(iso_ava, "structural_category", "type", run, "isoform", "ava", acc)
        plot_categories(iso_ava, "subcategory", "type", run,  "isoform", "ava", acc)

        # -------------6-------------
        # relate the gene type to their gene in sqanti
        gene_ref = pd.merge(left=merged_all, right=gene_type, how='left', left_on='associated_gene', right_on='ref_gene')
        # ------------6.1------------
        # basic analysis
        gene_nlr = gene_ref.loc[gene_ref["type"] == "nlr"]
        gene_busco = gene_ref.loc[gene_ref["type"] == "busco"]
        gene_house = gene_ref.loc[gene_ref["type"] == "housekeeping"]
        gene_all = pd.concat([gene_nlr,gene_busco,gene_house])
        # plot exon + length distribution
        plot_distribution(gene_all, "exons", "type", run, "gene", "reference", acc)
        plot_distribution(gene_all, "length", "type", run,  "gene", "reference", acc)
        # plot category and subcategory
        plot_categories(gene_all, "structural_category", "type", run, "gene", "reference", acc)
        plot_categories(gene_all, "subcategory", "type", run,  "gene", "reference", acc)
        # ------------6.2------------
        # all genes as background, reference genes on top
        gene_background = merged_all.copy()
        gene_background["ref_isoform"] = "None"
        gene_background["type"] = "all"
        gene_background["ref_gene"] = "None"
        gene_background_all = pd.concat([gene_all,gene_background], ignore_index=True)
        # plot exon + length distribution
        plot_distribution(gene_background_all, "exons", "type", run, "gene", "background", acc)
        plot_distribution(gene_background_all, "length", "type", run,  "gene", "background", acc)
        # plot category and subcategory
        plot_categories(gene_background_all, "structural_category", "type", run, "gene", "background", acc)
        plot_categories(gene_background_all, "subcategory", "type", run,  "gene", "background", acc)
        # ------------6.3------------
        # rest vs. busco vs. house vs nlr.
        gene_ava = gene_ref.fillna("rest")
        # plot exon + length distribution
        plot_distribution(gene_ava, "exons", "type", run, "gene", "ava", acc)
        plot_distribution(gene_ava, "length", "type", run,  "gene", "ava", acc)
        # plot category and subcategory
        plot_categories(gene_ava, "structural_category", "type", run, "gene", "ava", acc)
        plot_categories(gene_ava, "subcategory", "type", run,  "gene", "ava", acc)

        # -------------7-------------
        # prepare the subcategory dataframe:
        idx=sub["structural_category"].value_counts().index
        cat_df = pd.DataFrame({"accession":[acc]})
        for cat in idx:
            cat_df[cat]=sub["structural_category"].value_counts()[cat]
        test=cat_df.set_index("accession").T[acc].sum()
        cat_df["sum"] = cat_df.set_index("accession").T[acc].sum()
        tama_subcat=pd.concat([tama_subcat, cat_df], ignore_index=True).fillna(0)
        
    tama_liftoff_df = tama_liftoff_df[["gene","isoform","accession","associated_gene","associated_transcript","exons","length","isoform_reads","gene_reads","structural_category","subcategory","ORF_seq"]]
    tama_liftoff_df.columns = ["gene","isoform","accession","associated_gene","associated_transcript","exons","length","isoform_read_support","gene_read_support","structural_category","subcategory","Sqanti_ORF_seq"]
    if run == "full":
        tama_liftoff_df.to_pickle("./tama_liftoff_sqanti_{}.pkl".format(run))
        tama_liftoff_df.to_csv("./tama_liftoff_sqanti_{}.tsv".format(run), sep="\t")

    # run analysis over the full dataframes
    os.makedirs("{}/{}/gene".format(run,"all"), exist_ok=True)
    
    # basic
    all_gene_ref = pd.merge(left=tama_liftoff_df, right=gene_type, how='left', left_on='associated_gene', right_on='ref_gene')
    all_gene_nlr = all_gene_ref.loc[all_gene_ref["type"] == "nlr"]
    all_gene_busco = all_gene_ref.loc[all_gene_ref["type"] == "busco"]
    all_gene_house = all_gene_ref.loc[all_gene_ref["type"] == "housekeeping"]
    all_gene_all = pd.concat([all_gene_nlr,all_gene_busco,all_gene_house])
    # plot exon + length distribution
    plot_distribution(all_gene_all, "exons", "type", run, "gene", "reference", "all")
    plot_distribution(all_gene_all, "length", "type", run, "gene", "reference", "all")
    # plot category and subcategory
    plot_categories(all_gene_all, "structural_category", "type", run, "gene", "reference", "all")
    plot_categories(all_gene_all, "subcategory", "type", run,  "gene", "reference", "all")

    # background
    all_background = tama_liftoff_df.copy()
    all_background["ref_isoform"] = "None"
    all_background["type"] = "all"
    all_background["ref_gene"] = "None"
    all_background_all = pd.concat([all_gene_all,all_background], ignore_index=True)
    # plot exon + length distribution
    plot_distribution(all_background_all, "exons", "type", run, "gene", "background", "all")
    plot_distribution(all_background_all, "length", "type", run, "gene", "background", "all")
    # plot category and subcategory
    plot_categories(all_background_all, "structural_category", "type", run, "gene", "background", "all")
    plot_categories(all_background_all, "subcategory", "type", run,  "gene", "background", "all")
    
    # all vs all
    all_gene_ava = all_gene_ref.fillna("rest")
    # plot exon + length distribution
    plot_distribution(all_gene_ava, "exons", "type", run, "gene", "ava", "all")
    plot_distribution(all_gene_ava, "length", "type", run, "gene", "ava", "all")
    # plot category and subcategory
    plot_categories(all_gene_ava, "structural_category", "type", run, "gene", "ava", "all")
    plot_categories(all_gene_ava, "subcategory", "type", run,  "gene", "ava", "all")
    
    #t = tama_subcat.copy()
    for cat in tama_subcat.set_index("accession").columns:
        tama_subcat["proportion"]=tama_subcat[cat]/tama_subcat["sum"]*100
        sns.barplot(data=tama_subcat, x="accession", y="proportion")
        plt.xticks(rotation=45, horizontalalignment='right')
        plt.ylabel("{} [%]".format(cat))
        plt.savefig("{}/all/all_tama_liftoff_{}.png".format(run,cat), bbox_inches='tight')
        plt.close()

  0%|                                                                                                                                                                                                                                                                                                                                                                 | 0/1 [00:00<?, ?it/s]
  0%|                                                                                                                                                                                                                                                                                                                                                                | 0/18 [00:00<?, ?it/s]
  6%|███████████████████                                                                                                                                                                                                                                                                                                                                     | 1/18 [00:39<11:16, 39.81s/it]
 11%|██████████████████████████████████████▏                                                                                                                                                                                                                                                                                                                 | 2/18 [01:10<09:11, 34.46s/it]
 17%|█████████████████████████████████████████████████████████▎                                                                                                                                                                                                                                                                                              | 3/18 [01:46<08:47, 35.19s/it]
 22%|████████████████████████████████████████████████████████████████████████████▍                                                                                                                                                                                                                                                                           | 4/18 [02:14<07:29, 32.12s/it]
 28%|███████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                                                                                                                                                                        | 5/18 [02:43<06:43, 31.01s/it]
 33%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                                                                                                                                     | 6/18 [03:18<06:29, 32.44s/it]
 39%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                                                                                                                                  | 7/18 [03:53<06:05, 33.25s/it]
 44%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                                                                                                               | 8/18 [04:34<05:59, 35.97s/it]
 50%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                                                                                            | 9/18 [05:09<05:19, 35.45s/it]
 56%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                                                                        | 10/18 [05:39<04:31, 33.95s/it]
 61%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                                                     | 11/18 [06:08<03:45, 32.29s/it]
 67%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                  | 12/18 [06:37<03:08, 31.43s/it]
 72%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                               | 13/18 [07:15<02:45, 33.17s/it]
 78%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                            | 14/18 [07:42<02:05, 31.44s/it]
 83%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                         | 15/18 [08:16<01:36, 32.21s/it]
 89%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                      | 16/18 [08:43<01:01, 30.58s/it]
 94%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                   | 17/18 [09:16<00:31, 31.46s/it]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 18/18 [09:46<00:00, 32.56s/it]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [14:29<00:00, 869.34s/it]

In [25]:
test=pd.read_pickle("tama_liftoff_sqanti_full.pkl")

In [ ]:
sns.displot(test, x="exons", hue = "accession", kind="kde",common_norm=False)
plt.savefig("tama_liftoff_exons_full.png", bbox_inches='tight')
plt.close()

In [ ]:
sns.displot(test, x="length", hue = "accession", kind="kde",common_norm=False)
plt.savefig("tama_liftoff_length_full.png", bbox_inches='tight')
plt.close()